name: Publish css-color-5 on /TR
on:
  pull_request:
  push:
    branches: [main]
    paths: 
      - "css-color-5/**"
  workflow_dispatch:

jobs:
  publish-TR-css-color-5:
    name: Publish css-color-5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: bikeshed
          SOURCE: css-color-5/Overview.bs
          DESTINATION: css-color-5/index.html
          BUILD_FAIL_ON: warning
          VALIDATE_MARKUP: false
          W3C_ECHIDNA_TOKEN: ${{ secrets.TR_TOKEN_CSS_COLOR_5 }}
          W3C_WG_DECISION_URL: https://www.w3.org/2025/08/21-css-minutes.html#fc30
          W3C_BUILD_OVERRIDE: |
            status: WD
