name: Publish css-fonts-4 on /TR
on:
  pull_request:
  push:
    branches: [main]
    paths: 
      - "css-fonts-4/**"
  workflow_dispatch:

jobs:
  publish-TR-css-fonts-4:
    name: Publish css-fonts-4
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: bikeshed
          SOURCE: css-fonts-4/Overview.bs
          DESTINATION: css-fonts-4/index.html
          BUILD_FAIL_ON: warning
          VALIDATE_MARKUP: false
          W3C_ECHIDNA_TOKEN: ${{ secrets.TR_TOKEN_CSS_FONTS_4}}
          W3C_WG_DECISION_URL: https://www.w3.org/2025/08/21-css-minutes.html#fc30
          W3C_BUILD_OVERRIDE: |
            status: WD
